name: Deploy static site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: plantchain-frontend/package-lock.json

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        working-directory: plantchain-frontend
        run: |
          npm ci || npm i

      - name: Build
        env:
          NEXT_PUBLIC_BASE_PATH: "/PlantChain"
          NEXT_TELEMETRY_DISABLED: "1"
        working-directory: plantchain-frontend
        run: |
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: plantchain-frontend/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


